// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"time"

	"github.com/TakuyaYagam1/VideoLibrary/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockCache
func (_mock *MockCache) Del(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockCache_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockCache_Expecter) Del(ctx interface{}, keys ...interface{}) *MockCache_Del_Call {
	return &MockCache_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockCache_Del_Call) Run(run func(ctx context.Context, keys ...string)) *MockCache_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCache_Del_Call) Return(err error) *MockCache_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Del_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockCache_Del_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrLoadVideos provides a mock function for the type MockCache
func (_mock *MockCache) GetOrLoadVideos(ctx context.Context, key string, ttl time.Duration, loadFn func(context.Context) ([]domain.Video, error)) ([]domain.Video, error) {
	ret := _mock.Called(ctx, key, ttl, loadFn)

	if len(ret) == 0 {
		panic("no return value specified for GetOrLoadVideos")
	}

	var r0 []domain.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, func(context.Context) ([]domain.Video, error)) ([]domain.Video, error)); ok {
		return returnFunc(ctx, key, ttl, loadFn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, func(context.Context) ([]domain.Video, error)) []domain.Video); ok {
		r0 = returnFunc(ctx, key, ttl, loadFn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Video)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, func(context.Context) ([]domain.Video, error)) error); ok {
		r1 = returnFunc(ctx, key, ttl, loadFn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetOrLoadVideos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrLoadVideos'
type MockCache_GetOrLoadVideos_Call struct {
	*mock.Call
}

// GetOrLoadVideos is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
//   - loadFn func(context.Context) ([]domain.Video, error)
func (_e *MockCache_Expecter) GetOrLoadVideos(ctx interface{}, key interface{}, ttl interface{}, loadFn interface{}) *MockCache_GetOrLoadVideos_Call {
	return &MockCache_GetOrLoadVideos_Call{Call: _e.mock.On("GetOrLoadVideos", ctx, key, ttl, loadFn)}
}

func (_c *MockCache_GetOrLoadVideos_Call) Run(run func(ctx context.Context, key string, ttl time.Duration, loadFn func(context.Context) ([]domain.Video, error))) *MockCache_GetOrLoadVideos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 func(context.Context) ([]domain.Video, error)
		if args[3] != nil {
			arg3 = args[3].(func(context.Context) ([]domain.Video, error))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCache_GetOrLoadVideos_Call) Return(videos []domain.Video, err error) *MockCache_GetOrLoadVideos_Call {
	_c.Call.Return(videos, err)
	return _c
}

func (_c *MockCache_GetOrLoadVideos_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration, loadFn func(context.Context) ([]domain.Video, error)) ([]domain.Video, error)) *MockCache_GetOrLoadVideos_Call {
	_c.Call.Return(run)
	return _c
}
