// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/TakuyaYagam1/VideoLibrary/backend/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVideoRepository creates a new instance of MockVideoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoRepository {
	mock := &MockVideoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVideoRepository is an autogenerated mock type for the VideoRepository type
type MockVideoRepository struct {
	mock.Mock
}

type MockVideoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoRepository) EXPECT() *MockVideoRepository_Expecter {
	return &MockVideoRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockVideoRepository
func (_mock *MockVideoRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Video, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Video, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Video); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Video)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVideoRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVideoRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockVideoRepository_GetByID_Call {
	return &MockVideoRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVideoRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVideoRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoRepository_GetByID_Call) Return(video domain.Video, err error) *MockVideoRepository_GetByID_Call {
	_c.Call.Return(video, err)
	return _c
}

func (_c *MockVideoRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Video, error)) *MockVideoRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementViewsWithOutbox provides a mock function for the type MockVideoRepository
func (_mock *MockVideoRepository) IncrementViewsWithOutbox(ctx context.Context, id uuid.UUID) (domain.Video, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViewsWithOutbox")
	}

	var r0 domain.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Video, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Video); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Video)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoRepository_IncrementViewsWithOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementViewsWithOutbox'
type MockVideoRepository_IncrementViewsWithOutbox_Call struct {
	*mock.Call
}

// IncrementViewsWithOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVideoRepository_Expecter) IncrementViewsWithOutbox(ctx interface{}, id interface{}) *MockVideoRepository_IncrementViewsWithOutbox_Call {
	return &MockVideoRepository_IncrementViewsWithOutbox_Call{Call: _e.mock.On("IncrementViewsWithOutbox", ctx, id)}
}

func (_c *MockVideoRepository_IncrementViewsWithOutbox_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVideoRepository_IncrementViewsWithOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoRepository_IncrementViewsWithOutbox_Call) Return(video domain.Video, err error) *MockVideoRepository_IncrementViewsWithOutbox_Call {
	_c.Call.Return(video, err)
	return _c
}

func (_c *MockVideoRepository_IncrementViewsWithOutbox_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Video, error)) *MockVideoRepository_IncrementViewsWithOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// ListVideos provides a mock function for the type MockVideoRepository
func (_mock *MockVideoRepository) ListVideos(ctx context.Context) ([]domain.Video, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListVideos")
	}

	var r0 []domain.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Video, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Video); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Video)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoRepository_ListVideos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVideos'
type MockVideoRepository_ListVideos_Call struct {
	*mock.Call
}

// ListVideos is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVideoRepository_Expecter) ListVideos(ctx interface{}) *MockVideoRepository_ListVideos_Call {
	return &MockVideoRepository_ListVideos_Call{Call: _e.mock.On("ListVideos", ctx)}
}

func (_c *MockVideoRepository_ListVideos_Call) Run(run func(ctx context.Context)) *MockVideoRepository_ListVideos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVideoRepository_ListVideos_Call) Return(videos []domain.Video, err error) *MockVideoRepository_ListVideos_Call {
	_c.Call.Return(videos, err)
	return _c
}

func (_c *MockVideoRepository_ListVideos_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Video, error)) *MockVideoRepository_ListVideos_Call {
	_c.Call.Return(run)
	return _c
}
