// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXUW/bNhD+KwS3R9mSHTdN9VZ03RIgG4KkycOKIDiLJ5uNRHIk5dQL/N+HI2VbjtV4",
	"6bZ2bzZ95H33fd8d6Ude6Npohco7nj9yV8yxhvDxvbXaXqIzWjmkBRBCeqkVVBdWG7ReouN5CZXDhJvO",
	"Eh0qwhaBrrDS0C6e8ysP0wpZDcVcKhxYBBEWkDIx2jPkCcfPUJsKec4XUqC+U9rflbpRgie8luoc1czP",
	"eT5KuF8aCnPeSjXjq4TX6BzMejKfNjWopwnb6J6cTGnP/lbOVcIt/tFIi4LnH2PdWxy3m3g9/YSFJ4yn",
	"CJWffyWvzoNv3H597xprUXkGxlSyAFpl85CIxS2hSNXUBFLf84QLnFkQKAjjtvrw0/MlthD6SjtThcUa",
	"lb+R+OC+skQp9su7CaJIgcrLUqLdlSwbnZSv4aQcZDieDl7Dq9eDN8VYDI7huHgzEVkxGk14wktta/A8",
	"500jBe9xz4JQ7ye/NgI8CqaaeoqW6ZJZLLQVKJipYDmF4p5Itt7twJocdVJK5Y8n0UuyJhWyTX6pPM7Q",
	"7vEcMEZIfVwHSl7alRapkjuC1E9xiCDzeFmj81CbXarH2fh4kB0PRqMPo3GeZXmW/d6llpga0N4+fktZ",
	"4Z0BaqS9yYDwgCh+vmKxQkZhTFtmmmklC/brxYRdX56zxqFg0yXzcwzkP7VC6F6XajXVYIVUs2FtJofn",
	"xvfznJe+Ojyv4lAKsbsw3mlrtAWPbFvy4XK/YPTfXmjw8b9g8Fh/1xtreEnXrvsdQKdJVer9Mi7fX31g",
	"by/OWKltMEqxISnyWMmpBbscbtK3Yp/HddpLKNC6eGA2HA0z4k0bVGAkz/nRMBse8YQT4sBkCkam0X30",
	"dYY9LXaJvrHKMaiqFkmNHgR4SJhURdWQemzbCsRJaATHQAlGtLBCN8qjDUpQa4duPRM85+fS+ZsIgHiO",
	"szeAGWdZvJOVRxVwda6J9JMjcOubP0xgj3XY+KPFkuf8h3T7RkjbB0Ia589qowtYC8soS18fVdL5IYW/",
	"eiGY5zDsvlB6cl8r/GywoOnt0C7Qxpt/GLzomroGu2ypY4s1dx5mjvzZLtxSbEfe9FGKVUpiEDyjXY/S",
	"m4vQBQN2lQuuhFZ/ktW2rqDApr1qFlA1uC9x534VqG/aNjFgoUYyBc8/9k+x6+uzn+g4SUttlymoQ3cK",
	"3m1LbxtMOvQfGGCr23/otefk/cJzok/nNW8dooPbJt/SbWdqAZUUrbaR84Bh8u0wRL0fwG2fsP/bttvo",
	"2zK2nvu9DRhfs38eHK7URs++gndb6hf0p+3J/6GTn7z5eyh724EsXYt62Up39P2ArP8mPNUuHsSKORb3",
	"HckibpKMooP2fVPpXBdQMYELrLQJDoixPOGNrXjO596bPE0riptr5/OT7CTjq9vVXwEAAP//HbwQlbAO",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
