// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXXW/bNhf+KwTf91K2ZcdNU90VXdcEyIYgaXKxIgiOxSObjURyJOXUC/zfh0PKthwr",
	"cdJtbTHsLqH58Zzn45C657mujFaovOPZPXf5DCsIf763VttzdEYrhzQAQkgvtYLyzGqD1kt0PCugdJhw",
	"0xqiTUVYItDlVhpaxTN+4WFSIqsgn0mFPYsgwgDSSYzW9HnC8QtUpkSe8bkUqG+U9jeFrpXgCa+kOkU1",
	"9TOeDRPuF4amOW+lmvJlwit0DqYdJx/XFaiHBzazO85kSnv2rDOXCbf4ey0tCp59inVvcFyv5+vJZ8w9",
	"YTxGKP3sK3l1Hnztdut7V1uLyjMwppQ50CibhYNYXBKKVHVFIPUtT7jAqQWBgjBuqg8/PV1iA6GrtBOV",
	"W6xQ+SuJd+4rS5Rit7yrIIoUqLwsJNptydLhUfEajopeiqNJ7zW8et17k49E7xAO8zdjkebD4ZgnvNC2",
	"As8zXtdS8A73zAn17uGXRoBHwVRdTdAyXTCLubYCBTMlLCaQ3xLJ1rstWOOD1pFS+cNx9JKsSIV0fb5U",
	"Hqdod3gOGCOkLq4DJS9NpUWq5IYgdVMcZpB5vKzQeajMNtWjdHTYSw97w+HH4ShL0yxNf2tTS0z1aG0X",
	"v4Us8cYABWmnMyDcIYqfL1iskNE0pi0z9aSUOfvlbMwuz09Z7VCwyYL5GQbyH1ohpNcNtJposEKqab8y",
	"4/194/t5zktf7u9XsSmFudsw3mlrtAWPbFPy/nIfMfqvLzT46G8weKy/7Y0VvKRt190E0G5SFXq3jPP3",
	"Fx/Z27MTVmgbjJKvSYo8lnJiwS766+MbsU/jOK0lFGhd3DDtD/sp8aYNKjCSZ/ygn/YPeMIJcWByAEYO",
	"ovvo3yl2ROwcfW2VY1CWDZIKPQjwkDCp8rIm9dgmCsRJCIJjoAQjWliua+XRBiUo2iGtJ4Jn/FQ6fxUB",
	"EM+x9wYwozSNd7LyqAKu1jUx+OwI3OrmDx3YYxUW/t9iwTP+v8HmjTBoHgiD2H+Wa13AWlhEWbpyVErn",
	"+zT91QvBPIVh+4XScfalwi8Gc+reDu0cbbz5+8GLrq4qsIuGOjZfcedh6sifzcA1zW3JO7iXYrlXY61W",
	"bpssmBRtgcmSHSI/0tu2Rf6AUeNgPQsVkhd49qm7eV1envxEe0gaasKloAqhFLydRm9rTFqs7+lby+u/",
	"aLFnOOsxJ60yE9w0/pZuOlFzKKVodI3kBgzjb4chcnAHbvNE/WFj9QGbVD0zVAPqcATOaNcRrfXr0oWI",
	"tNthaPXQCEO90jYxpIl1836bQ1njbqRaj1aB+qq5e/616Xrkjd6l8oq3FtH/he5HD91a34ax1WOqM4Dx",
	"E/GPvbcZxejJT8udW+q42fkfdPKDD+kOyt62IEvXoF400h18PyCrb++H2sWNWD7D/LYlWcRNktHsoH1X",
	"VzrVOZRM4BxLbYID4lye8NqWPOMz7002GJQ0b6adz47So5Qvr5d/BgAA///k5IIPBRIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
