// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Current application health status.
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus Current application health status.
type HealthResponseStatus string

// IncrementViewsResponse defines model for IncrementViewsResponse.
type IncrementViewsResponse struct {
	// Id Video identifier.
	Id openapi_types.UUID `json:"id"`

	// Views Updated number of recorded playback starts.
	Views int64 `json:"views"`
}

// Video defines model for Video.
type Video struct {
	// CreatedAt Video creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// FilePath SeaweedFS object path or public MP4 URL used by the player.
	FilePath string `json:"file_path"`

	// Id Video identifier.
	Id openapi_types.UUID `json:"id"`

	// Title Human-readable video title.
	Title string `json:"title"`

	// Views Number of recorded playback starts.
	Views int64 `json:"views"`
}
