// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID           pgtype.UUID        `json:"id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	ProcessingAt pgtype.Timestamptz `json:"processing_at"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
	Attempts     int32              `json:"attempts"`
	FailureError pgtype.Text        `json:"failure_error"`
}

type Video struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	FilePath  string             `json:"file_path"`
	Views     int64              `json:"views"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
