// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchUnprocessedOutbox = `-- name: FetchUnprocessedOutbox :many
SELECT
    id,
    event_type,
    payload,
    created_at,
    processed_at
FROM outbox_events
WHERE processed_at IS NULL
ORDER BY created_at, id
LIMIT $1
`

func (q *Queries) FetchUnprocessedOutbox(ctx context.Context, limitCount int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, fetchUnprocessedOutbox, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (
    id,
    event_type,
    payload
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    event_type,
    payload,
    created_at,
    processed_at
`

type InsertOutboxEventParams struct {
	ID        pgtype.UUID `json:"id"`
	EventType string      `json:"event_type"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.ID, arg.EventType, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markOutboxProcessed = `-- name: MarkOutboxProcessed :exec
UPDATE outbox_events
SET processed_at = now()
WHERE id = $1
  AND processed_at IS NULL
`

func (q *Queries) MarkOutboxProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxProcessed, id)
	return err
}
