// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVideoByID = `-- name: GetVideoByID :one
SELECT
    id,
    title,
    file_path,
    views,
    created_at
FROM videos
WHERE id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.Views,
		&i.CreatedAt,
	)
	return i, err
}

const incrementViewsWithOutbox = `-- name: IncrementViewsWithOutbox :one
WITH updated_video AS (
    UPDATE videos
    SET views = videos.views + 1
    WHERE videos.id = $1
    RETURNING videos.id, videos.views
),
inserted_event AS (
    INSERT INTO outbox_events (
        id,
        event_type,
        payload
    )
    SELECT
        $2::uuid,
        'cache.invalidate_videos_list',
        jsonb_build_object(
            'video_id', updated_video.id,
            'views', updated_video.views
        )
    FROM updated_video
    RETURNING id
)
SELECT updated_video.views
FROM updated_video
JOIN inserted_event ON true
`

type IncrementViewsWithOutboxParams struct {
	VideoID       pgtype.UUID `json:"video_id"`
	OutboxEventID pgtype.UUID `json:"outbox_event_id"`
}

func (q *Queries) IncrementViewsWithOutbox(ctx context.Context, arg IncrementViewsWithOutboxParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementViewsWithOutbox, arg.VideoID, arg.OutboxEventID)
	var views int32
	err := row.Scan(&views)
	return views, err
}

const listVideos = `-- name: ListVideos :many
SELECT
    id,
    title,
    file_path,
    views,
    created_at
FROM videos
ORDER BY created_at DESC, id
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.Views,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
